import {
    // CustomPre,
    // CustomCode,
    // CustomDiv,
    CustomLink,
    InfoQuote,
    ThoughtQuote,
    AnnouncementQuote,
    BlockQuote,
    IdeaQuote,
    WarningQuote,
    CustomUnorderedList,
    CustomListItem,
    CustomImage,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    Definition,
    YouTubeVideo,
    GitHubRepository,
} from "./MDXComponents";

import Codeblock from "./codeblock";

const MDXComponents = {
    // div: CustomDiv,
    a: CustomLink,
    // pre: CustomPre,
    // code: CustomCode,
    code: Codeblock,
    ul: CustomUnorderedList,
    li: CustomListItem,
    h1: h1,
    h2: h2,
    h3: h3,
    h4: h4,
    h5: h5,
    h6: h6,
    InfoQuote,
    ThoughtQuote,
    AnnouncementQuote,
    BlockQuote,
    IdeaQuote,
    WarningQuote,
    Image: CustomImage,
    Definition: Definition,
    YouTubeVideo: YouTubeVideo,
    GitHubRepository: GitHubRepository,
};

export default MDXComponents;
