name: frontend:build_and_deploy

on:
    push:
        branches:
            - master
        pull_request:
            branches:
                - master
        paths:
            - "frontend/**"

jobs:
    build:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - name: Build docker image and publish it to registry.davidapps.dev
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: davidilie/personal-website
                  registry: registry.davidapps.dev
                  username: DavidIlie
                  password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
                  dockerfile: Dockerfile
                  tags: frontend
                  workdir: frontend/
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Kubernetes
              uses: actions-hub/kubectl@master
              env:
                  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
              with:
                  args: rollout restart deploy frontend -n davidilie-com
