name: frontend:build_and_deploy

on:
    push:
        branches:
            - master
        paths:
            - "frontend/**"

jobs:
    build_and_deploy:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        runs-on: ubuntu-latest
        steps:
            - name: "Build:checkout"
              uses: actions/checkout@v2
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: registry.davidapps.dev
                  username: DavidIlie
                  password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
            - name: Build and publish Docker image
              run: |
                  cd frontend && docker build -t ghcr.io/davidilie/sharex-upload-server/web:latest .
                  docker push ghcr.io/davidilie/sharex-upload-server/web:latest
            - name: "Set Kubernetes Context"
              uses: Azure/k8s-set-context@v1
              with:
                  method: kubeconfig
                  kubeconfig: ${{ secrets.KUBE_CONFIG }}
            - name: "Restart deployment"
              run: kubectl rollout restart deploy frontend -n davidilie.com
