name: frontend:build_and_deploy

on:
    push:
        paths:
            - "frontend/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Publish to GitLab Container Registry
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: davidilie/projects
                  registry: registry.gitlab.com
                  username: DavidIlie
                  password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
                  dockerfile: frontend/Dockerfile
                  tags: davidilie-frontend
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Kubernetes
              uses: actions-hub/kubectl@master
              env:
                  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
              with:
                  args: rollout restart deploy frontend -n davidilie-com
