name: github_cron:update

on:
   schedule:
      # 3x/day during daytime hours (UTC): 08:00, 14:00, 20:00
      - cron: "0 8,14,20 * * *"

jobs:
   execute:
      runs-on: ubuntu-latest
      steps:
         - uses: satak/webrequest-action@master
           with:
              url: https://davidilie.com/api/cron/github?secret=${{ secrets.REPO_JOB_SECRET }}
              method: GET
