name: github_cron:update

on:
   schedule:
      # Hourly, on the hour (UTC).
      - cron: "0 * * * *"

jobs:
   execute:
      runs-on: davidapps-linux-x64
      steps:
         - uses: satak/webrequest-action@master
           with:
              url: https://davidilie.com/api/cron/github?secret=${{ secrets.REPO_JOB_SECRET }}
              method: GET
