name: identity:build_and_deploy

on:
    push:
        branches:
            - master
        paths:
            - "identity/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v2
              with:
                  node-version: "15"
            - run: cd identity && yarn
            - name: Publish to GitLab Container Registry
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: davidilie/personal-website
                  registry: registry.davidapps.dev
                  username: DavidIlie
                  password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
                  dockerfile: Dockerfile
                  tags: identity
                  workdir: identity/
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Kubernetes
              uses: actions-hub/kubectl@master
              env:
                  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
              with:
                  args: rollout restart deploy identity -n davidilie-com
